CREATE TABLE IF NOT EXISTS sensores (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS leituras (
    id SERIAL PRIMARY KEY,
    sensor_id INTEGER REFERENCES sensores(id),
    valor FLOAT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);