CREATE TABLE IF NOT EXISTS sensores (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS leituras (
    id SERIAL PRIMARY KEY,
    sensor_id INTEGER REFERENCES sensores(id),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS valores (
    id SERIAL PRIMARY KEY,
    leitura_id INTEGER REFERENCES leituras(id),
    valor FLOAT
);